/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2001704324455690151L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"org.example.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favorite_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"favorite_color\",\"type\":[\"string\",\"null\"]},{\"name\":\"favorite_car\",\"type\":{\"type\":\"record\",\"name\":\"FavoriteCar\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"color\",\"type\":\"string\"}]}},{\"name\":\"portfolio_list\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Portfolio\",\"fields\":[{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"position\",\"type\":\"string\"},{\"name\":\"years\",\"type\":\"int\"},{\"name\":\"salary\",\"type\":\"double\"},{\"name\":\"efficiency_score\",\"type\":\"float\"},{\"name\":\"responsibilities\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<User> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<User> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<User> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<User> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<User> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this User to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a User from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a User instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static User fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence name;
  private Integer favorite_number;
  private CharSequence favorite_color;
  private FavoriteCar favorite_car;
  private java.util.List<Portfolio> portfolio_list;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public User() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param favorite_number The new value for favorite_number
   * @param favorite_color The new value for favorite_color
   * @param favorite_car The new value for favorite_car
   * @param portfolio_list The new value for portfolio_list
   */
  public User(CharSequence name, Integer favorite_number, CharSequence favorite_color, FavoriteCar favorite_car, java.util.List<Portfolio> portfolio_list) {
    this.name = name;
    this.favorite_number = favorite_number;
    this.favorite_color = favorite_color;
    this.favorite_car = favorite_car;
    this.portfolio_list = portfolio_list;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return favorite_number;
    case 2: return favorite_color;
    case 3: return favorite_car;
    case 4: return portfolio_list;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: name = (CharSequence)value$; break;
    case 1: favorite_number = (Integer)value$; break;
    case 2: favorite_color = (CharSequence)value$; break;
    case 3: favorite_car = (FavoriteCar)value$; break;
    case 4: portfolio_list = (java.util.List<Portfolio>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'favorite_number' field.
   * @return The value of the 'favorite_number' field.
   */
  public Integer getFavoriteNumber() {
    return favorite_number;
  }


  /**
   * Sets the value of the 'favorite_number' field.
   * @param value the value to set.
   */
  public void setFavoriteNumber(Integer value) {
    this.favorite_number = value;
  }

  /**
   * Gets the value of the 'favorite_color' field.
   * @return The value of the 'favorite_color' field.
   */
  public CharSequence getFavoriteColor() {
    return favorite_color;
  }


  /**
   * Sets the value of the 'favorite_color' field.
   * @param value the value to set.
   */
  public void setFavoriteColor(CharSequence value) {
    this.favorite_color = value;
  }

  /**
   * Gets the value of the 'favorite_car' field.
   * @return The value of the 'favorite_car' field.
   */
  public FavoriteCar getFavoriteCar() {
    return favorite_car;
  }


  /**
   * Sets the value of the 'favorite_car' field.
   * @param value the value to set.
   */
  public void setFavoriteCar(FavoriteCar value) {
    this.favorite_car = value;
  }

  /**
   * Gets the value of the 'portfolio_list' field.
   * @return The value of the 'portfolio_list' field.
   */
  public java.util.List<Portfolio> getPortfolioList() {
    return portfolio_list;
  }


  /**
   * Sets the value of the 'portfolio_list' field.
   * @param value the value to set.
   */
  public void setPortfolioList(java.util.List<Portfolio> value) {
    this.portfolio_list = value;
  }

  /**
   * Creates a new User RecordBuilder.
   * @return A new User RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new User RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new User RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new User RecordBuilder by copying an existing User instance.
   * @param other The existing instance to copy.
   * @return A new User RecordBuilder
   */
  public static Builder newBuilder(User other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for User instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    private CharSequence name;
    private Integer favorite_number;
    private CharSequence favorite_color;
    private FavoriteCar favorite_car;
    private FavoriteCar.Builder favorite_carBuilder;
    private java.util.List<Portfolio> portfolio_list;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[1].schema(), other.favorite_number);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[2].schema(), other.favorite_color);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.favorite_car)) {
        this.favorite_car = data().deepCopy(fields()[3].schema(), other.favorite_car);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasFavoriteCarBuilder()) {
        this.favorite_carBuilder = FavoriteCar.newBuilder(other.getFavoriteCarBuilder());
      }
      if (isValidValue(fields()[4], other.portfolio_list)) {
        this.portfolio_list = data().deepCopy(fields()[4].schema(), other.portfolio_list);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing User instance
     * @param other The existing instance to copy.
     */
    private Builder(User other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[1].schema(), other.favorite_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[2].schema(), other.favorite_color);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.favorite_car)) {
        this.favorite_car = data().deepCopy(fields()[3].schema(), other.favorite_car);
        fieldSetFlags()[3] = true;
      }
      this.favorite_carBuilder = null;
      if (isValidValue(fields()[4], other.portfolio_list)) {
        this.portfolio_list = data().deepCopy(fields()[4].schema(), other.portfolio_list);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public Builder setName(CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'favorite_number' field.
      * @return The value.
      */
    public Integer getFavoriteNumber() {
      return favorite_number;
    }


    /**
      * Sets the value of the 'favorite_number' field.
      * @param value The value of 'favorite_number'.
      * @return This builder.
      */
    public Builder setFavoriteNumber(Integer value) {
      validate(fields()[1], value);
      this.favorite_number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'favorite_number' field has been set.
      * @return True if the 'favorite_number' field has been set, false otherwise.
      */
    public boolean hasFavoriteNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'favorite_number' field.
      * @return This builder.
      */
    public Builder clearFavoriteNumber() {
      favorite_number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'favorite_color' field.
      * @return The value.
      */
    public CharSequence getFavoriteColor() {
      return favorite_color;
    }


    /**
      * Sets the value of the 'favorite_color' field.
      * @param value The value of 'favorite_color'.
      * @return This builder.
      */
    public Builder setFavoriteColor(CharSequence value) {
      validate(fields()[2], value);
      this.favorite_color = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'favorite_color' field has been set.
      * @return True if the 'favorite_color' field has been set, false otherwise.
      */
    public boolean hasFavoriteColor() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'favorite_color' field.
      * @return This builder.
      */
    public Builder clearFavoriteColor() {
      favorite_color = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'favorite_car' field.
      * @return The value.
      */
    public FavoriteCar getFavoriteCar() {
      return favorite_car;
    }


    /**
      * Sets the value of the 'favorite_car' field.
      * @param value The value of 'favorite_car'.
      * @return This builder.
      */
    public Builder setFavoriteCar(FavoriteCar value) {
      validate(fields()[3], value);
      this.favorite_carBuilder = null;
      this.favorite_car = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'favorite_car' field has been set.
      * @return True if the 'favorite_car' field has been set, false otherwise.
      */
    public boolean hasFavoriteCar() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'favorite_car' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public FavoriteCar.Builder getFavoriteCarBuilder() {
      if (favorite_carBuilder == null) {
        if (hasFavoriteCar()) {
          setFavoriteCarBuilder(FavoriteCar.newBuilder(favorite_car));
        } else {
          setFavoriteCarBuilder(FavoriteCar.newBuilder());
        }
      }
      return favorite_carBuilder;
    }

    /**
     * Sets the Builder instance for the 'favorite_car' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public Builder setFavoriteCarBuilder(FavoriteCar.Builder value) {
      clearFavoriteCar();
      favorite_carBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'favorite_car' field has an active Builder instance
     * @return True if the 'favorite_car' field has an active Builder instance
     */
    public boolean hasFavoriteCarBuilder() {
      return favorite_carBuilder != null;
    }

    /**
      * Clears the value of the 'favorite_car' field.
      * @return This builder.
      */
    public Builder clearFavoriteCar() {
      favorite_car = null;
      favorite_carBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'portfolio_list' field.
      * @return The value.
      */
    public java.util.List<Portfolio> getPortfolioList() {
      return portfolio_list;
    }


    /**
      * Sets the value of the 'portfolio_list' field.
      * @param value The value of 'portfolio_list'.
      * @return This builder.
      */
    public Builder setPortfolioList(java.util.List<Portfolio> value) {
      validate(fields()[4], value);
      this.portfolio_list = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'portfolio_list' field has been set.
      * @return True if the 'portfolio_list' field has been set, false otherwise.
      */
    public boolean hasPortfolioList() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'portfolio_list' field.
      * @return This builder.
      */
    public Builder clearPortfolioList() {
      portfolio_list = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public User build() {
      try {
        User record = new User();
        record.name = fieldSetFlags()[0] ? this.name : (CharSequence) defaultValue(fields()[0]);
        record.favorite_number = fieldSetFlags()[1] ? this.favorite_number : (Integer) defaultValue(fields()[1]);
        record.favorite_color = fieldSetFlags()[2] ? this.favorite_color : (CharSequence) defaultValue(fields()[2]);
        if (favorite_carBuilder != null) {
          try {
            record.favorite_car = this.favorite_carBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("favorite_car"));
            throw e;
          }
        } else {
          record.favorite_car = fieldSetFlags()[3] ? this.favorite_car : (FavoriteCar) defaultValue(fields()[3]);
        }
        record.portfolio_list = fieldSetFlags()[4] ? this.portfolio_list : (java.util.List<Portfolio>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<User>
    WRITER$ = (org.apache.avro.io.DatumWriter<User>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<User>
    READER$ = (org.apache.avro.io.DatumReader<User>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    if (this.favorite_number == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.favorite_number);
    }

    if (this.favorite_color == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.favorite_color);
    }

    this.favorite_car.customEncode(out);

    long size0 = this.portfolio_list.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (Portfolio e0: this.portfolio_list) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.favorite_number = null;
      } else {
        this.favorite_number = in.readInt();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.favorite_color = null;
      } else {
        this.favorite_color = in.readString(this.favorite_color instanceof Utf8 ? (Utf8)this.favorite_color : null);
      }

      if (this.favorite_car == null) {
        this.favorite_car = new FavoriteCar();
      }
      this.favorite_car.customDecode(in);

      long size0 = in.readArrayStart();
      java.util.List<Portfolio> a0 = this.portfolio_list;
      if (a0 == null) {
        a0 = new SpecificData.Array<Portfolio>((int)size0, SCHEMA$.getField("portfolio_list").schema());
        this.portfolio_list = a0;
      } else a0.clear();
      SpecificData.Array<Portfolio> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<Portfolio>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          Portfolio e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new Portfolio();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.favorite_number = null;
          } else {
            this.favorite_number = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.favorite_color = null;
          } else {
            this.favorite_color = in.readString(this.favorite_color instanceof Utf8 ? (Utf8)this.favorite_color : null);
          }
          break;

        case 3:
          if (this.favorite_car == null) {
            this.favorite_car = new FavoriteCar();
          }
          this.favorite_car.customDecode(in);
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<Portfolio> a0 = this.portfolio_list;
          if (a0 == null) {
            a0 = new SpecificData.Array<Portfolio>((int)size0, SCHEMA$.getField("portfolio_list").schema());
            this.portfolio_list = a0;
          } else a0.clear();
          SpecificData.Array<Portfolio> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<Portfolio>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              Portfolio e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new Portfolio();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










